#!/usr/bin/sh

xrandr --output HDMI-0 --mode 1920x1080 --output DP-2 --mode 1920x1080 --primary --right-of HDMI-0
bspc monitor DP-2 -s HDMI-0

bspc monitor DP-2 -d 1 2 
bspc monitor HDMI-0 -d 3 4
bspc wm -O DP-2 HDMI-0

I=1
  M=$(bspc query -M | wc -l)
  if [[ "$M" == 1 ]]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9
  elif [[ "$M" == 2 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d 1 2
     bspc monitor $(bspc query -M | awk NR==2) -d 3 4
  elif [[ "$M" == 3 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3
     bspc monitor $(bspc query -M | awk NR==2) -d 4 5 6 
     bspc monitor $(bspc query -M | awk NR==3) -d 7 8 9
  elif [[ "$M" == 4 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d 1 2 3
     bspc monitor $(bspc query -M | awk NR==2) -d 4 5 6 
     bspc monitor $(bspc query -M | awk NR==3) -d 7 8 
     bspc monitor $(bspc query -M | awk NR==4) -d 9 0
  elif [[ "$M" == 5 ]]; then
     bspc monitor $(bspc query -M | awk NR==1) -d 1 2
     bspc monitor $(bspc query -M | awk NR==2) -d 3 4
     bspc monitor $(bspc query -M | awk NR==3) -d 5 6
     bspc monitor $(bspc query -M | awk NR==4) -d 6 7
     bspc monitor $(bspc query -M | awk NR==5) -d 8 9
  else
    for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$I" \
        -d $I/{a,b,c}
     let I++
     done
  fi


picom -b -f --config .config/picom/picom.conf
polybar &
sxhkd &

bash ~/.config/polybar/launch.sh --colorblocks
nitrogen --restore &

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
